# Microsoft Teams push — turn any TIDE report (an array of objects) into an Adaptive
# Card and POST it to a Power Automate "Workflows" incoming webhook. This is the
# supported successor to the retired Office 365 connector webhooks: the webhook needs
# no auth beyond its secret URL, and the same path works unattended from a runbook.

function New-IaAdaptiveCard {
    <#
    .SYNOPSIS
        Build an Adaptive Card (v1.5) object from a title + summary + rows.
    .DESCRIPTION
        Renders the rows as an Adaptive Card `Table` (firstRowAsHeaders). Markup is
        stripped from every cell so the card shows clean text, and the row set is
        capped at -MaxRows with a "… and N more" note.
    #>
    param(
        [Parameter(Mandatory)][string]$Title,
        [string]$Summary,
        [object[]]$Rows = @(),
        [int]$MaxRows = 15,
        [string[]]$Column
    )

    $body = [System.Collections.Generic.List[object]]::new()
    $body.Add([ordered]@{ type = 'TextBlock'; text = $Title; size = 'Large'; weight = 'Bolder'; wrap = $true })
    if ($Summary) { $body.Add([ordered]@{ type = 'TextBlock'; text = $Summary; isSubtle = $true; wrap = $true; spacing = 'Small' }) }

    $rows = @($Rows)
    if ($rows.Count -gt 0) {
        $cols  = if ($Column) { @($Column) } else { @($rows[0].PSObject.Properties.Name) }
        $shown = @($rows | Select-Object -First $MaxRows)

        $tableRows = [System.Collections.Generic.List[object]]::new()
        # header
        $tableRows.Add([ordered]@{ type = 'TableRow'; cells = @(foreach ($c in $cols) {
            [ordered]@{ type = 'TableCell'; items = @([ordered]@{ type = 'TextBlock'; text = "$c"; weight = 'Bolder'; wrap = $true }) }
        }) })
        # data
        foreach ($r in $shown) {
            $tableRows.Add([ordered]@{ type = 'TableRow'; cells = @(foreach ($c in $cols) {
                $val = Strip-IaMarkup ([string]($r.$c ?? ''))
                [ordered]@{ type = 'TableCell'; items = @([ordered]@{ type = 'TextBlock'; text = $val; wrap = $true }) }
            }) })
        }

        $body.Add([ordered]@{
            type              = 'Table'
            columns           = @(foreach ($c in $cols) { @{ width = 1 } })
            rows              = $tableRows.ToArray()
            firstRowAsHeaders = $true
            gridStyle         = 'accent'
        })
        if ($rows.Count -gt $shown.Count) {
            $body.Add([ordered]@{ type = 'TextBlock'; text = "… and $($rows.Count - $shown.Count) more row(s)."; isSubtle = $true; wrap = $true })
        }
    } else {
        $body.Add([ordered]@{ type = 'TextBlock'; text = '(no rows)'; isSubtle = $true; wrap = $true })
    }

    $body.Add([ordered]@{ type = 'TextBlock'; text = "Generated by TIDE · $(Get-Date -Format 'yyyy-MM-dd HH:mm')"; size = 'Small'; isSubtle = $true; wrap = $true; separator = $true })

    [ordered]@{
        type      = 'AdaptiveCard'
        '$schema' = 'http://adaptivecards.io/schemas/adaptive-card.json'
        version   = '1.5'
        body      = $body.ToArray()
    }
}

function New-IaTeamsMessage {
    # Wrap an Adaptive Card in the message envelope a Workflows incoming webhook expects.
    param([Parameter(Mandatory)]$Card)
    [ordered]@{
        type        = 'message'
        attachments = @([ordered]@{
            contentType = 'application/vnd.microsoft.card.adaptive'
            content     = $Card
        })
    }
}

function Invoke-IaWebhookPost {
    # The single real outbound HTTP call (kept tiny so tests can mock it).
    param([Parameter(Mandatory)][string]$Uri, [Parameter(Mandatory)][string]$Json)
    Invoke-RestMethod -Method POST -Uri $Uri -ContentType 'application/json; charset=utf-8' -Body $Json
}

function Invoke-IaPushToTeams {
    # TUI helper: resolve a webhook URL (session cache / env / prompt), push the rows,
    # and report the result. Used by the table viewer's `p` keybind.
    param([object[]]$Data, [string]$Title = 'TIDE report', [string]$Color = 'turquoise2')
    $url = if ($script:IaTeamsWebhook) { $script:IaTeamsWebhook } else { $env:TIDE_TEAMS_WEBHOOK }
    if (-not $url) {
        $url = Read-IaText -Question 'Teams webhook URL (Power Automate Workflows incoming webhook)'
        if ([string]::IsNullOrWhiteSpace($url)) { Write-IaHost '[yellow]Cancelled — no webhook URL.[/]'; Read-IaPause | Out-Null; return }
        $script:IaTeamsWebhook = $url   # remember for the rest of the session
    }
    try {
        Send-IntuneReportToTeams -InputObject $Data -Title $Title -WebhookUrl $url -Confirm:$false | Out-Null
        Write-IaHost "[$Color]✓ Pushed '$Title' ($(@($Data).Count) row(s)) to Teams.[/]"
    } catch {
        Write-IaHost "[coral]Teams push failed:[/] $($_.Exception.Message)"
    }
    Read-IaPause | Out-Null
}
